### ISSUE TITLE
Get underlying xml from element

### ISSUE THREAD

**Issue by TheSachin** [goetas-webservices/xsd-reader#25]
Hi is there a way to get underlying xml  of an element?

**Comment by goetas** [comment]
This library is built with the propose to abstract from the underlying xml representation, so it is not possible and is not planned to be. Sorry.

If you need to access the underlying data, they should be integrated inside the library data structures

**Comment by TheSachin** [comment]
I guess i kind of agree with you. I need to see if the structure of the element has sequence or switch. Currently library is only providing me type elements underneath.
`$reader = new SchemaReader();`
   ` $schema = $reader->readFile($file);`
    `$element = $schema->getElement($name);`
    `$fields = $this->ProcessChildren($element);`
`$element->getType()->getElements()`
Hence i thought if i could get xml then i could process child.

**Comment by TheSachin** [comment]
hi goetas ,could you suggest an alternative.

**Comment by goetas** [comment]
As said, the project was planned to hide the underlying xml...
If you want to do it, you can modify the schema reader and the type objects
to expose it... But i Really do not suggest it.

Which data do you need?

On 12 Dec 2017 07:01, "Sachin" <notifications@github.com> wrote:

hi goetas ,could you suggest an alternative.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/goetas-webservices/xsd-reader/issues/25#issuecomment-350953861>,
or mute the thread

**Comment by TheSachin** [comment]
>Which data do you need?
Basically i need to identify sequence and choice tags, to process children of that tag accordingly. I totally agree with your notion of not messing directly with xml.
